# Site settings
title: Erueat's Tech Home
email: erueat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a tech blog of Erueat Chan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erueat.tk" # the base hostname & protocol for your site
twitter_username: erueat
github_username:  erueat

# Build settings
markdown: kramdown
