# Site settings
title: 陈猿猿的技术窝
email: erueat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  分享技术，交流技术
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erueat.tk" # the base hostname & protocol for your site
twitter_username: erueat
github_username:  erueat

# Build settings
markdown: kramdown
